k2/urls.py
from django.urls import path
from k2 import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.KartaSearchFormView.as_view(), name='karta-search'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('update/<int:pk>', views.KartaUpdate.as_view(), name='karta-update'),
    path('auto/', views.KartaAutocompleteView, name='karta-auto'),
]

stava/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('k2.urls')),
]

k2/models.py
from django.db import models
from django.db.models import Q
from django.core.validators import RegexValidator


class Karta(models.Model):
    cislo = models.SmallIntegerField(unique=True, help_text='Číslo karty')
    cislo_str = models.CharField(
            validators=[RegexValidator(regex='^.{5}$', message='Délka musí být 5 znaků', code='nomatch')],
            max_length=5, unique=True, help_text='Karta č.')
    nick = models.CharField(max_length=55, blank=True, help_text='Jméno držitele karty')
    celkem_nakupu = models.SmallIntegerField(default=0, help_text='Celkový počet všech nákupů nad 50 kč')
    stav = models.SmallIntegerField(default=0, help_text='Počet bodů na kartě 0-9')
    celkem_nakupu_do_50 = models.SmallIntegerField(default=0, help_text='Celkový počet všech nákupů')
    stav_do_50 = models.SmallIntegerField(default=0, help_text='Počet bodů na kartě 0-9, nákup do 50 kč')
    aktivni = models.BooleanField(
        default=True, help_text='Pokud se karta ztratí nebo bude smazána, nastavit False')
    datum_zalozeni = models.DateTimeField(
        auto_now_add=True, help_text='Datum aktivace a předání karty držiteli')
    datum_posledni_zmeny = models.DateTimeField(
        auto_now=True, help_text='Datum poslední provedené úpravy na kartě')

    class Meta:
        ordering = ['-datum_posledni_zmeny', '-cislo']
        verbose_name = 'karta'
        verbose_name_plural = 'karty'

    def __str__(self):
        return f'karta {self.cislo_str}'

    @classmethod
    def cislo_nove_karty(cls):
        ''' Vrátí nejnižší volné číslo karty v pořadí pro přiřazení k nové kartě'''
        try:
            return cls.objects.all().order_by('cislo').last().cislo + 1
        except AttributeError:
            return 1

    def get_cislo_str(self):
        ''' převod čísla karty do formátu "0000X" '''
        return '{0:0>5}'.format(self.cislo)

    def deaktivuj(self):
        self.aktivni = False
        self.save()

    @classmethod
    def autocomplete(cls, bar):
        ''' Vrátí hodnoty 'číslo_str' a 'nick' jako jediný seznam'''
        data = [j for i in cls.objects.filter(Q(cislo_str__contains=bar)|Q(nick__icontains=bar)).values_list('cislo_str', 'nick') for j in i if j != '']
        return data

    @classmethod
    def generuj_karty(cls, pocet=1):
        ''' Generuj předaný počet nových prázdných karet - vyhni se kolizím'''

        cislo = cls.cislo_nove_karty()
        for i in range(pocet):
            karta = cls(cislo=cislo)
            karta.cislo_str = karta.get_cislo_str()
            karta.save()
            cislo += 1

k2/forms.py
from django import forms


class KartaSearchForm(forms.Form):
    search = forms.CharField(label='číslo karty / přezdívka', max_length=33)

k2/views.py
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Q
from k2.models import Karta
from .forms import KartaSearchForm


class KartaSearchFormView(LoginRequiredMixin, FormView):
    login_url = '/login/'
    template_name = "k2/karta_search.html"
    form_class = KartaSearchForm
    success_url = "/update/"

    def form_valid(self, form):
        cd = form.cleaned_data
        raw = cd['search']
        if raw:
            try:
                karta = Karta.objects.get(Q(cislo_str=raw)|Q(nick__iexact=raw))
            except (Karta.DoesNotExist, ValueError):
                form.add_error('search', ValidationError('Hledaný výraz nebyl nalezen'))
                return super().form_invalid(form)

            self.success_url = f'/update/{karta.pk}'
        return super().form_valid(form)


class KartaUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Karta
    fields = ['nick', 'stav', 'stav_do_50']
    template_name = 'k2/karta_update.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['karta'] = self.model.objects.get(pk=pk)
        return context

    def form_valid(self, form, **kwargs):
        cd = form.cleaned_data
        nick = cd.get('nick')
        if nick:
            if nick.isnumeric():
                form.add_error('nick', ValidationError('Přezdívka se nesmí skládat pouze z čísel'))
                return super().form_invalid(form)
            if len(nick) < 3:
                form.add_error('nick', ValidationError('Minimální délka přezdívky jsou 3 znaky'))
                return super().form_invalid(form)
            # validace duplicitnich nicku, vynech sam sebe
            dupl_qs = self.model.objects.filter(nick__iexact=nick)
            if dupl_qs:
                dupl = dupl_qs.first()
                if dupl.pk != form.instance.pk:
                    form.add_error('nick', ValidationError('Tato přezdívka již existuje'))
                    return super().form_invalid(form)

        return super().form_valid(form)


def KartaAutocompleteView(request):
    if request.is_ajax():
        dotaz = request.GET.get('term', '')
        data = Karta.autocomplete(dotaz) if dotaz else  Karta.autocomplete(5)
    else:
        data = 'fail'

    return JsonResponse(data, safe=False)

k2/templates/k2/karta_search.html
{%extends 'k2/pattern.html'%}
{%load static%}
{%block titulek%}hledej kartu{%endblock%}
{%block obsah%}
    <div id='kartaSearch'>
        <form method="post">{%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="" style="background-image: url('{% static "k2/img/confirm.png"%}'" />
        </form>
	</div>
{%endblock%}

k2/templates/k2/karta_update.html
{%extends 'k2/pattern.html'%}
{%load static%}
{%block titulek%}úprava karty{%endblock%}
{%block obsah%}
    <div id='karta_update'>
        {%if karta%}
            <form method="post" id='karta_update_form'>{%csrf_token%}
                <span class="update_form_field">
                <label for="id_cislo_karty">číslo karty</label>
                <input type='text' name='cislo_karty' id='id_cislo_karty' value="{{karta.cislo_str}}" disabled/>
                </span>
                <span class="update_form_field">
                <label for="id_nick">přezdívka</label>
                {%if form.nick.errors%}
                    {{form.nick.errors}}
                {%endif%}
                {{form.nick}}
                </span>

                <div id='do50'>
                    <input type='hidden' name='stav_do_50' id='id_stav_do_50' value="{{karta.stav_do_50}}"/>
                    <div id='puvodni_stav_do_50'>zboží do 50kč <strong>{{karta.stav_do_50}}</strong></div>
                    <div id='novy_stav_do_50'>
                        <button id='minus_do_50' style="background-image: url('{% static "k2/img/minus.png"%}'"></button>
                        <span>{{karta.stav_do_50}}</span>
                        <button id='plus_do_50' style="background-image: url('{% static "k2/img/plus.png"%}'"></button>
                    </div>
                </div>

                <div id='nad50'>
                    <input type='hidden' name='stav' id='id_stav' value="{{karta.stav}}"/>
                    <div id='puvodni_stav'>zboží nad 50kč<strong>{{karta.stav}}</strong></div>
                    <div id='novy_stav'>
                        <button id='minus' style="background-image: url('{% static "k2/img/minus.png"%}'"></button>
                        <span>{{karta.stav}}</span>
                        <button id='plus' style="background-image: url('{% static "k2/img/plus.png"%}'"></button>
                    </div>
                </div>

                <div id='potvrzeni'>
                    <button type="submit" id='storno' formaction='{%url 'karta-search'%}' style="background-image: url('{% static "k2/img/storno.png"%}'"></button>
                    <button type="submit" id='confirm' style="background-image: url('{% static "k2/img/confirm.png"%}'"></button>
                </div>
            </form>
        {%else%}
            <h2>Nebyla vybrána žádná karta</h2>
        {%endif%}
	</div>
{%endblock%}

k2/templates/k2/pattern.html
<!DOCTYPE html>
{% load static %}

<html lang="cs-cz">
    <head>
        <meta charset="utf-8" />
        <title>{%block title%}Hustá šťáva{%endblock%}</title>
		<!--<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Questrial">-->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
        <link rel="stylesheet" type="text/css" href="{% static 'k2/jquery-ui.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'k2/main.css' %}">
        <script src="{%static 'k2/jquery-3.5.1.min.js'%}"></script>
        <script src="{%static 'k2/jquery-ui.min.js'%}"></script>
        <script src="{%static 'k2/main.js'%}"></script>
		{%block head%}
		{%endblock%}
    </head>

    <body>
		{%block obsah%}
      	{%endblock%}
    </body>
</html>